# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Delta3DWeightsC <- function(vx, Datasample) {
    .Call(`_DatabionicSwarm_Delta3DWeightsC`, vx, Datasample)
}

DijkstraSSSP <- function(Adj, Costs, source) {
    .Call(`_DatabionicSwarm_DijkstraSSSP`, Adj, Costs, source)
}

PswarmCurrentRadiusC2botsPositive <- function(AllDataBotsPosOld, Radius, DataDists, IndPossibleDBPosR, RadiusPositionsschablone, pp, Nullpunkt, Lines, Columns, nBots, limit, steigungsverlaufind, StressConstAditiv, debug) {
    .Call(`_DatabionicSwarm_PswarmCurrentRadiusC2botsPositive`, AllDataBotsPosOld, Radius, DataDists, IndPossibleDBPosR, RadiusPositionsschablone, pp, Nullpunkt, Lines, Columns, nBots, limit, steigungsverlaufind, StressConstAditiv, debug)
}

findPossiblePositionsCsingle <- function(RadiusPositionsschablone, jumplength, alpha, Lines) {
    .Call(`_DatabionicSwarm_findPossiblePositionsCsingle`, RadiusPositionsschablone, jumplength, alpha, Lines)
}

rDistanceToroidCsingle <- function(AllDataBotsPosX, AllDataBotsPosY, AllallowedDBPosR0, Lines, Columns, Nullpunkt) {
    .Call(`_DatabionicSwarm_rDistanceToroidCsingle`, AllDataBotsPosX, AllDataBotsPosY, AllallowedDBPosR0, Lines, Columns, Nullpunkt)
}

trainstepC <- function(vx, vy, DataSampled, BMUsampled, Lines, Columns, Radius, toroid) {
    .Call(`_DatabionicSwarm_trainstepC`, vx, vy, DataSampled, BMUsampled, Lines, Columns, Radius, toroid)
}

trainstepC2 <- function(esomwts, aux, DataSampled, BMUsampled, Lines, Columns, Weights, Radius, toroid) {
    .Call(`_DatabionicSwarm_trainstepC2`, esomwts, aux, DataSampled, BMUsampled, Lines, Columns, Weights, Radius, toroid)
}

